name:                haskell-graphql
version:             0.1.0.0
github:              "aztecrex/haskell-graphql"
license:             BSD3
author:              "Greg Wiley <aztecrex@jammm.com>"
maintainer:          "Greg Wiley <aztecrex@jammm.com>"
copyright:           "2018 Greg Wiley"

extra-source-files:
- README.md

description: See README.md on GitHub at <https://github.com/aztecrex/haskell-graphql#readme>

dependencies:
- base >= 4.7 && < 5
# - aeson
- attoparsec
# - bytestring
- text
- unordered-containers
# - time

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  haskell-graphql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-graphql

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - MonoLocalBinds
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies

